AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  
Globals:
  Function:
    Timeout: 3
 
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
        
  FunctionA:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdaA/
      Handler: lambdaA.lambdaHandler
      Runtime: nodejs22.x
      Architectures: [x86_64]
      Events:
        S3ObjectCreated:
          Type: S3
          Properties:
            Bucket: !Ref S3Bucket
            Events:
              - s3:ObjectCreated:*  
      EventInvokeConfig:          
        MaximumRetryAttempts: 2
        MaximumEventAgeInSeconds: 3600
        DestinationConfig:
          OnSuccess:
            Type: Lambda
            Destination: !GetAtt FunctionB.Arn
          
  FunctionB:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdaB/
      Handler: lambdaB.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64

  AllowDestinationInvokeB:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref FunctionB
      Principal: lambda.amazonaws.com
      
      